import 'package:riverpod_annotation/riverpod_annotation.dart';

import '../../institution/application/institution_config_loader.dart';
import '../../institution/domain/academic_structure.dart';
import '../domain/timetable.dart';
import '../domain/timetable_entry.dart';

part 'timetable_engine.g.dart';

/// Service for generating and managing institution-specific timetables
class TimetableEngine {
  final InstitutionConfigLoader _configLoader;

  TimetableEngine(this._configLoader);

  /// Generate a default timetable structure based on institution type
  Future<List<TimetableEntry>> generateDefaultTimetable({
    required String schoolId,
    required String institutionTypeId,
    required int classId,
    required int sectionId,
    required String academicYear,
  }) async {
    // Load institution-specific academic configuration
    final academicConfig = await _configLoader.loadAcademicConfig(institutionTypeId);
    
    // Get supported period types for this institution
    final periodTypes = academicConfig.supportedPeriodTypes;
    
    // Generate default timetable entries based on institution type
    final entries = <TimetableEntry>[];
    
    // Generate entries for each day of the week (Monday to Friday)
    for (var dayOfWeek = 1; dayOfWeek <= 5; dayOfWeek++) {
      // For each period type supported by the institution
      for (final periodType in periodTypes) {
        // Create a default entry for this period
        final entry = TimetableEntry(
          id: '', // Will be generated by database
          schoolId: schoolId,
          timetableId: '', // Will be set when timetable is created
          dayOfWeek: dayOfWeek,
          periodId: periodType.id,
          subjectId: null, // No subject assigned by default
          teacherId: null, // No teacher assigned by default
          roomId: null, // No room assigned by default
          notes: 'Default ${periodType.name} period',
          isSubstitute: false,
          substituteTeacherId: null,
          createdAt: DateTime.now(),
          updatedAt: DateTime.now(),
        );
        
        entries.add(entry);
      }
    }
    
    return entries;
  }

  /// Validate timetable entries against institution constraints
  Future<List<String>> validateTimetable({
    required String institutionTypeId,
    required List<TimetableEntry> entries,
    required List<AcademicPeriod> availablePeriods,
  }) async {
    final errors = <String>[];
    
    // Load institution-specific constraints
    final academicConfig = await _configLoader.loadAcademicConfig(institutionTypeId);
    
    // Check for maximum periods per day constraint
    final maxPeriodsPerDay = academicConfig.maxPeriodsPerDay;
    final periodsByDay = <int, int>{};
    for (final entry in entries) {
      periodsByDay[entry.dayOfWeek] = (periodsByDay[entry.dayOfWeek] ?? 0) + 1;
    }
    
    for (final entry in periodsByDay.entries) {
      if (entry.value > maxPeriodsPerDay) {
        errors.add('Day ${_getDayName(entry.key)} has ${entry.value} periods, maximum allowed is $maxPeriodsPerDay');
      }
    }
      
    // Check for minimum break periods constraint
    final minBreakPeriods = academicConfig.minBreakPeriods;
    if (minBreakPeriods != null) {
      // This would require more complex logic to detect consecutive teaching periods
      // and ensure adequate breaks are scheduled
      // For now, we'll just note that this validation is institution-specific
      errors.add('Break period validation required for ${academicConfig.institutionType}');
    }
    
    // Check if all periods are within available period types
    final supportedPeriodIds = academicConfig.supportedPeriodTypes.map((p) => p.id).toSet();
    for (final entry in entries) {
      if (!supportedPeriodIds.contains(entry.periodId)) {
        errors.add('Period ID ${entry.periodId} is not supported for this institution type');
      }
    }
    
    return errors;
  }

  /// Get institution-specific timetable constraints
  Future<Map<String, dynamic>> getTimetableConstraints(String institutionTypeId) async {
    final academicConfig = await _configLoader.loadAcademicConfig(institutionTypeId);
    
    return {
      'maxPeriodsPerDay': academicConfig.maxPeriodsPerDay,
      'minBreakPeriods': academicConfig.minBreakPeriods,
      'supportedPeriodTypes': academicConfig.supportedPeriodTypes,
      'defaultStartTime': academicConfig.defaultStartTime,
      'defaultEndTime': academicConfig.defaultEndTime,
      'institutionType': academicConfig.institutionType,
    };
  }

  String _getDayName(int dayOfWeek) {
    switch (dayOfWeek) {
      case 1: return 'Monday';
      case 2: return 'Tuesday';
      case 3: return 'Wednesday';
      case 4: return 'Thursday';
      case 5: return 'Friday';
      case 6: return 'Saturday';
      case 7: return 'Sunday';
      default: return 'Unknown';
    }
  }
}

/// Riverpod provider for the timetable engine
@riverpod
TimetableEngine timetableEngine(TimetableEngineRef ref) {
  final configLoader = ref.watch(institutionConfigLoaderProvider);
  return TimetableEngine(configLoader);
}