import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../application/certificates_providers.dart';
import '../../domain/certificate.dart';
import '../../domain/certificate_template.dart';
import '../../domain/certificate_type.dart';
import '../../../authentication/application/auth_providers.dart';
import '../../../student_management/application/student_providers.dart';

class GenerateCertificateDialog extends ConsumerStatefulWidget {
  final CertificateTemplate template;

  const GenerateCertificateDialog({
    super.key,
    required this.template,
  });

  @override
  ConsumerState<GenerateCertificateDialog> createState() =>
      _GenerateCertificateDialogState();
}

class _GenerateCertificateDialogState
    extends ConsumerState<GenerateCertificateDialog> {
  final _formKey = GlobalKey<FormState>();
  String? _selectedStudentId;
  String? _selectedStaffId;
  DateTime _issuedDate = DateTime.now();
  final _notesController = TextEditingController();

  @override
  void dispose() {
    _notesController.dispose();
    super.dispose();
  }

  Future<void> _generate() async {
    if (!_formKey.currentState!.validate()) return;

    final repo = ref.read(certificatesRepositoryProvider);
    final currentUser = ref.read(currentUserProvider).value;
    if (currentUser?.id == null) return;

    // Determine recipient
    final recipientId = _selectedStudentId ?? _selectedStaffId;
    if (recipientId == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Please select a recipient')),
      );
      return;
    }

    // TODO: Fetch recipient name from student/staff data
    final recipientName = 'Recipient Name'; // Placeholder

    final certificate = Certificate(
      id: '',
      schoolId: repo.schoolId ?? '',
      templateId: widget.template.id,
      certificateNumber: '', // Will be generated by database
      certificateType: widget.template.certificateType,
      recipientType: _selectedStudentId != null
          ? RecipientType.student
          : RecipientType.staff,
      recipientId: recipientId,
      recipientName: recipientName,
      issuedDate: _issuedDate,
      issuedBy: currentUser!.id,
      certificateData: null, // TODO: Create proper CertificateData object based on template type
      notes: _notesController.text.trim().isEmpty
          ? null
          : _notesController.text.trim(),
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    );

    try {
      await repo.generateCertificate(certificate);
      if (mounted) {
        Navigator.pop(context);
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('Certificate generated successfully'),
          ),
        );
        ref.invalidate(certificatesProvider);
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Error: $e')),
        );
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final studentsAsync = ref.watch(studentsProvider);

    return Dialog(
      child: Container(
        width: MediaQuery.of(context).size.width * 0.9,
        padding: const EdgeInsets.all(16),
        child: Form(
          key: _formKey,
          child: SingleChildScrollView(
            child: Column(
              mainAxisSize: MainAxisSize.min,
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                Text(
                  'Generate ${widget.template.certificateType.displayName}',
                  style: const TextStyle(
                    fontSize: 20,
                    fontWeight: FontWeight.bold,
                  ),
                ),
                const SizedBox(height: 16),
                if (widget.template.templateType == TemplateType.student ||
                    widget.template.templateType == TemplateType.both)
                  studentsAsync.when(
                    data: (students) {
                      return DropdownButtonFormField<String>(
                        decoration: const InputDecoration(
                          labelText: 'Select Student',
                          border: OutlineInputBorder(),
                        ),
                        items: students.map((student) {
                          return DropdownMenuItem(
                            value: student.id,
                            child: Text(
                              '${student.fullName} (${student.admissionNo})',
                            ),
                          );
                        }).toList(),
                        onChanged: (value) {
                          setState(() {
                            _selectedStudentId = value;
                            _selectedStaffId = null;
                          });
                        },
                        validator: (value) {
                          if (widget.template.templateType ==
                                  TemplateType.student &&
                              value == null) {
                            return 'Please select a student';
                          }
                          return null;
                        },
                      );
                    },
                    loading: () => const CircularProgressIndicator(),
                    error: (error, stack) => Text('Error: $error'),
                  ),
                const SizedBox(height: 16),
                ListTile(
                  title: const Text('Issued Date'),
                  subtitle: Text(
                    '${_issuedDate.year}-${_issuedDate.month}-${_issuedDate.day}',
                  ),
                  trailing: const Icon(Icons.calendar_today),
                  onTap: () async {
                    final picked = await showDatePicker(
                      context: context,
                      initialDate: DateTime.now(),
                      firstDate: DateTime(2000),
                      lastDate: DateTime(2100),
                    );
                    if (picked != null) {
                      setState(() => _issuedDate = picked);
                    }
                  },
                ),
                const SizedBox(height: 16),
                TextFormField(
                  controller: _notesController,
                  decoration: const InputDecoration(
                    labelText: 'Notes (Optional)',
                    border: OutlineInputBorder(),
                  ),
                  maxLines: 3,
                ),
                const SizedBox(height: 16),
                Row(
                  mainAxisAlignment: MainAxisAlignment.end,
                  children: [
                    TextButton(
                      onPressed: () => Navigator.pop(context),
                      child: const Text('Cancel'),
                    ),
                    const SizedBox(width: 8),
                    ElevatedButton(
                      onPressed: _generate,
                      child: const Text('Generate'),
                    ),
                  ],
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

