import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../application/messaging_providers.dart';
import '../../domain/circular.dart';
import '../../domain/messaging_type.dart';
import '../../../authentication/application/auth_providers.dart';

class CircularFormDialog extends ConsumerStatefulWidget {
  const CircularFormDialog({super.key});

  @override
  ConsumerState<CircularFormDialog> createState() => _CircularFormDialogState();
}

class _CircularFormDialogState extends ConsumerState<CircularFormDialog> {
  final _formKey = GlobalKey<FormState>();
  final _titleController = TextEditingController();
  final _contentController = TextEditingController();
  CircularType _circularType = CircularType.general;
  TargetAudience _targetAudience = TargetAudience.all;
  DateTime _issuedDate = DateTime.now();
  DateTime? _effectiveDate;
  DateTime? _expiryDate;
  bool _requiresAcknowledgment = false;

  @override
  void dispose() {
    _titleController.dispose();
    _contentController.dispose();
    super.dispose();
  }

  Future<void> _selectDate(
    BuildContext context,
    Function(DateTime) onDateSelected,
  ) async {
    final picked = await showDatePicker(
      context: context,
      initialDate: DateTime.now(),
      firstDate: DateTime(2000),
      lastDate: DateTime(2100),
    );
    if (picked != null) {
      onDateSelected(picked);
    }
  }

  Future<void> _submit() async {
    if (!_formKey.currentState!.validate()) return;

    final repo = ref.read(messagingRepositoryProvider);
    final currentUser = ref.read(currentUserProvider).value;
    if (currentUser?.id == null) return;

    final circular = Circular(
      id: '',
      schoolId: repo.schoolId ?? '',
      circularNumber: '', // Will be generated by the database
      title: _titleController.text.trim(),
      content: _contentController.text.trim(),
      circularType: _circularType,
      targetAudience: _targetAudience,
      issuedBy: currentUser!.id,
      issuedDate: _issuedDate,
      effectiveDate: _effectiveDate,
      expiryDate: _expiryDate,
      isActive: true,
      requiresAcknowledgment: _requiresAcknowledgment,
      createdAt: DateTime.now(),
      updatedAt: DateTime.now(),
    );

    try {
      await repo.createCircular(circular);
      if (mounted) {
        Navigator.pop(context);
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Circular created successfully')),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Error creating circular: $e')),
        );
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    return Dialog(
      child: Container(
        width: MediaQuery.of(context).size.width * 0.9,
        padding: const EdgeInsets.all(16),
        child: Form(
          key: _formKey,
          child: SingleChildScrollView(
            child: Column(
              mainAxisSize: MainAxisSize.min,
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: [
                const Text(
                  'Create Circular',
                  style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold),
                ),
                const SizedBox(height: 16),
                TextFormField(
                  controller: _titleController,
                  decoration: const InputDecoration(
                    labelText: 'Title',
                    border: OutlineInputBorder(),
                  ),
                  validator: (value) {
                    if (value == null || value.trim().isEmpty) {
                      return 'Please enter a title';
                    }
                    return null;
                  },
                ),
                const SizedBox(height: 16),
                TextFormField(
                  controller: _contentController,
                  decoration: const InputDecoration(
                    labelText: 'Content',
                    border: OutlineInputBorder(),
                  ),
                  maxLines: 5,
                  validator: (value) {
                    if (value == null || value.trim().isEmpty) {
                      return 'Please enter content';
                    }
                    return null;
                  },
                ),
                const SizedBox(height: 16),
                DropdownButtonFormField<CircularType>(
                  value: _circularType,
                  decoration: const InputDecoration(
                    labelText: 'Type',
                    border: OutlineInputBorder(),
                  ),
                  items: CircularType.values.map((type) {
                    return DropdownMenuItem(
                      value: type,
                      child: Text(type.displayName),
                    );
                  }).toList(),
                  onChanged: (value) {
                    if (value != null) {
                      setState(() => _circularType = value);
                    }
                  },
                ),
                const SizedBox(height: 16),
                DropdownButtonFormField<TargetAudience>(
                  value: _targetAudience,
                  decoration: const InputDecoration(
                    labelText: 'Target Audience',
                    border: OutlineInputBorder(),
                  ),
                  items: TargetAudience.values.map((audience) {
                    return DropdownMenuItem(
                      value: audience,
                      child: Text(audience.displayName),
                    );
                  }).toList(),
                  onChanged: (value) {
                    if (value != null) {
                      setState(() => _targetAudience = value);
                    }
                  },
                ),
                const SizedBox(height: 16),
                ListTile(
                  title: const Text('Issued Date'),
                  subtitle: Text('${_issuedDate.year}-${_issuedDate.month}-${_issuedDate.day}'),
                  trailing: const Icon(Icons.calendar_today),
                  onTap: () => _selectDate(context, (date) {
                    setState(() => _issuedDate = date);
                  }),
                ),
                ListTile(
                  title: const Text('Effective Date (Optional)'),
                  subtitle: Text(_effectiveDate != null
                      ? '${_effectiveDate!.year}-${_effectiveDate!.month}-${_effectiveDate!.day}'
                      : 'Not set'),
                  trailing: const Icon(Icons.calendar_today),
                  onTap: () => _selectDate(context, (date) {
                    setState(() => _effectiveDate = date);
                  }),
                ),
                ListTile(
                  title: const Text('Expiry Date (Optional)'),
                  subtitle: Text(_expiryDate != null
                      ? '${_expiryDate!.year}-${_expiryDate!.month}-${_expiryDate!.day}'
                      : 'Not set'),
                  trailing: const Icon(Icons.calendar_today),
                  onTap: () => _selectDate(context, (date) {
                    setState(() => _expiryDate = date);
                  }),
                ),
                const SizedBox(height: 8),
                CheckboxListTile(
                  title: const Text('Requires Acknowledgment'),
                  value: _requiresAcknowledgment,
                  onChanged: (value) {
                    setState(() => _requiresAcknowledgment = value ?? false);
                  },
                ),
                const SizedBox(height: 16),
                Row(
                  mainAxisAlignment: MainAxisAlignment.end,
                  children: [
                    TextButton(
                      onPressed: () => Navigator.pop(context),
                      child: const Text('Cancel'),
                    ),
                    const SizedBox(width: 8),
                    ElevatedButton(
                      onPressed: _submit,
                      child: const Text('Create'),
                    ),
                  ],
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}

